### ISSUE TITLE
Incorrect packages being used

### ISSUE THREAD

**Issue by dannyb101** [aws-samples/videos-transfer-vimeo#2]
I am getting the below error when trying to use this tool. `urlparse` was renamed to `urllib.parse` in python3, therefore the vimeo package is not useable in this repo, rendering the tool unusable

```
Traceback (most recent call last):
  File "/Users/danharling/Documents/projects/videos-transfer-vimeo/videos-transfer-vimeo.py", line 7, in <module>
    import vimeo
  File "/Users/danharling/Documents/projects/videos-transfer-vimeo/env/lib/python3.9/site-packages/vimeo/__init__.py", line 8, in <module>
    from vimeo.client import Client
  File "/Users/danharling/Documents/projects/videos-transfer-vimeo/env/lib/python3.9/site-packages/vimeo/client.py", line 5, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
```

**Comment by dmtr33** [comment]
It seems like I have mistakenly added the `vimeo` module to the step-by-step, when the correct module should be `PyVimeo`. Let me know if uninstalling `vimeo` with pip and installing `PyVimeo` works

**Comment by dmtr33** [comment]
It seems like I have mistakenly added the `vimeo` module to the step-by-step, when the correct module should be `PyVimeo`. Let me know if uninstalling `vimeo` with pip and installing `PyVimeo` works

**Comment by dannyb101** [comment]
Yes pip installing PyVimeo works, thanks!
