### ISSUE TITLE
TypeError: 'Response' object is not callable

### ISSUE THREAD

**Issue by dannyb101** [aws-samples/videos-transfer-vimeo#3]
Getting the below error when trying to run the script

```
Traceback (most recent call last):
  File "/project/videos-transfer-vimeo/videos-transfer-vimeo.py", line 65, in <module>
    videos.extend(future.result().json()['data'])
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs
```

**Comment by dmtr33** [comment]
Can you send the whole error message please?

**Comment by dmtr33** [comment]
Closing, fix merged
