### ISSUE TITLE
Connection timeout error

### ISSUE THREAD

**Issue by neeravnuk** [aws-samples/videos-transfer-vimeo#5]
I am getting an API time-out error and have tried reducing the number of parallel threads but have had no luck. Here is the error I am getting 

````
.local/lib/python3.9/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.2.0) or chardet (2.0.3)/charset_normalizer (3.3.2)doesn't match a supported version!
  warnings.warn(
<vimeo.client.VimeoClient object at 0xffff710ee7f0>
1107
Traceback (most recent call last):
  File "/home/ssm-user/.local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.vimeo.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/videos-transfer-vimeo/videos-transfer-vimeo.py", line 64, in <module>
    response = client.get('/me/videos', params={"per_page":50, 'page':i})
  File "/home/ssm-user/.local/lib/python3.9/site-packages/vimeo/client.py", line 75, in caller
    response = request_func(url, **kwargs)
  File "/home/ssm-user/.local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/ssm-user/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ssm-user/.local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ssm-user/.local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/ssm-user/.local/lib/python3.9/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.vimeo.com', port=443): Read timed out. (read timeout=30)
````

**Comment by neeravnuk** [comment]
Ultimately, I have to remove the parallelism and use the single-thread approach with time. sleep to resolve the connection reset issue.
